merged <- SplitObject(merged_seurat, split.by = 'AVM')
cellchat.avm <- createCellChat(object = merged$AVM, group.by = "clusters5")
cellchat.ctrl <- createCellChat(object = merged$CTRL, group.by = "clusters5")
cellchat.avm@DB <- CellChatDB.human
cellchat.ctrl@DB <- CellChatDB.human
cellchat.avm <- subsetData(cellchat5.avm)
cellchat5.ctrl <- subsetData(cellchat.ctrl)
cellchat.avm <- identifyOverExpressedGenes(cellchat.avm)
cellchat.avm <- identifyOverExpressedInteractions(cellchat.avm)
cellchat.avm <- projectData(cellchat.avm, PPI.human)
cellchat.ctrl <- identifyOverExpressedGenes(cellchat.ctrl)
cellchat.ctrl <- identifyOverExpressedInteractions(cellchat.ctrl)
cellchat.ctrl <- projectData(cellchat.ctrl, PPI.human)
cellchat.ctrl <- computeCommunProb(cellchat.ctrl)
cellchat.ctrl <- filterCommunication(cellchat.ctrl, min.cells = 20)
cellchat.avm <- computeCommunProb(cellchat.avm)
cellchat.avm <- filterCommunication(cellchat.avm, min.cells = 20)
cellchat.avm <- computeCommunProbPathway(cellchat.avm)
cellchat.ctrl <- computeCommunProbPathway(cellchat.ctrl)
cellchat.ctrl <- aggregateNet(cellchat.ctrl)
cellchat.avm <- aggregateNet(cellchat.avm)
cellchat.avm <- netAnalysis_computeCentrality(cellchat.avm, slot.name = "netP") 
cellchat.ctrl <- netAnalysis_computeCentrality(cellchat.ctrl, slot.name = "netP") 
